// Lingue disponibili
export const availableLanguages = [
  { code: 'it', name: 'Italiano' },
  { code: 'en', name: 'Inglese' },
  { code: 'fr', name: 'Francese' },
  { code: 'es', name: 'Spagnolo' },
  { code: 'de', name: 'Tedesco' },
  { code: 'pt', name: 'Portoghese' },
  { code: 'ru', name: 'Russo' },
  { code: 'zh', name: 'Cinese' },
  { code: 'ja', name: 'Giapponese' },
  { code: 'ar', name: 'Arabo' }
];

// Lingue effettivamente tradotte (solo quelle che abbiamo completato)
export const translatedLanguages = [
  { code: 'it', name: 'Italiano' },
  { code: 'en', name: 'Inglese' },
  { code: 'fr', name: 'Francese' },
  { code: 'es', name: 'Spagnolo' },
  { code: 'de', name: 'Tedesco' },
  { code: 'ar', name: 'Arabo' },
  { code: 'zh', name: 'Cinese' }
];

// Interessi standardizzati disponibili
export const availableInterests = [
  'Cucina',
  'Viaggi',
  'Musica',
  'Cinema',
  'Libri',
  'Sport',
  'Arte',
  'Fotografia',
  'Tecnologia',
  'Scienza',
  'Storia',
  'Filosofia',
  'Psicologia',
  'Medicina',
  'Economia',
  'Politica',
  'Ambiente',
  'Animali',
  'Giardinaggio',
  'Fai da te',
  'Collezionismo',
  'Giochi da tavolo',
  'Videogiochi',
  'Danza',
  'Teatro',
  'Poesia',
  'Scrittura',
  'Pittura',
  'Scultura',
  'Architettura',
  'Design',
  'Moda',
  'Bellezza',
  'Fitness',
  'Yoga',
  'Meditazione',
  'Spiritualità',
  'Religione',
  'Astronomia',
  'Geografia',
  'Lingue straniere',
  'Cultura',
  'Tradizioni',
  'Folclore',
  'Mitologia',
  'Archeologia',
  'Antropologia',
  'Sociologia',
  'Pedagogia',
  'Diritto',
  'Giornalismo',
  'Marketing',
  'Imprenditoria',
  'Finanza',
  'Investimenti',
  'Criptovalute',
  'Blockchain',
  'Intelligenza artificiale',
  'Machine learning',
  'Robotica',
  'Spazio',
  'Oceani',
  'Montagne',
  'Foreste',
  'Agricoltura',
  'Viticultura',
  'Birra',
  'Vino',
  'Caffè',
  'Tè',
  'Cioccolato',
  'Dolci',
  'Panificazione',
  'Pasticceria',
  'Mixology',
  'Cocktail',
  'Veganismo',
  'Vegetarianesimo',
  'Pescatarianesimo',
  'Keto',
  'Paleo',
  'Gluten-free',
  'Bio',
  'Sostenibilità',
  'Zero waste',
  'Riciclo',
  'Energia rinnovabile',
  'Auto elettriche',
  'Biciclette',
  'Escursionismo',
  'Alpinismo',
  'Subacquea',
  'Surf',
  'Snowboard',
  'Sci',
  'Tennis',
  'Calcio',
  'Basket',
  'Volley',
  'Nuoto',
  'Corsa',
  'Ciclismo',
  'Pilates',
  'Crossfit',
  'Arti marziali',
  'Boxe',
  'Kickboxing',
  'Judo',
  'Karate',
  'Taekwondo',
  'Aikido',
  'Tai Chi',
  'Qi Gong',
  'Reiki',
  'Ayurveda',
  'Omeopatia',
  'Naturopatia',
  'Erboristeria',
  'Aromaterapia',
  'Cristalloterapia',
  'Astrologia',
  'Tarocchi',
  'Numerologia',
  'Feng Shui',
  'Vastu',
  'Feng Shui',
  'Minimalismo',
  'Decluttering',
  'Organizzazione',
  'Produttività',
  'Time management',
  'Leadership',
  'Public speaking',
  'Negoziazione',
  'Problem solving',
  'Creatività',
  'Innovazione',
  'Startup',
  'E-commerce',
  'Social media',
  'Content creation',
  'Podcasting',
  'Videomaking',
  'Streaming',
  'Gaming',
  'E-sports',
  'Cosplay',
  'LARP',
  'Roleplay',
  'Dungeons & Dragons',
  'Magic: The Gathering',
  'Pokémon',
  'Anime',
  'Manga',
  'Comics',
  'Supereroi',
  'Fantasy',
  'Sci-fi',
  'Horror',
  'Thriller',
  'Romance',
  'Mystery',
  'Crime',
  'Western',
  'Documentari',
  'Reality TV',
  'Talk show',
  'Stand-up comedy',
  'Improvvisazione',
  'Magia',
  'Circo',
  'Acrobazie',
  'Giocoleria',
  'Equilibrismo',
  'Trapezio',
  'Clown',
  'Mimo',
  'Ventriloquismo',
  'Mentalismo',
  'Ipnotismo',
  'Parapsicologia',
  'Ufologia',
  'Criptozoologia',
  'Teorie del complotto',
  'Conspiracy theories',
  'Alternative history',
  'Pseudoscienza',
  'New Age',
  'Esoterismo',
  'Occultismo',
  'Wicca',
  'Paganesimo',
  'Sciamanesimo',
  'Buddhismo',
  'Induismo',
  'Islam',
  'Cristianesimo',
  'Ebraismo',
  'Sikhismo',
  'Jainismo',
  'Zoroastrismo',
  'Baha\'i',
  'Scientology',
  'Ateismo',
  'Agnosticismo',
  'Umanesimo',
  'Secolarismo',
  'Laicismo',
  'Femminismo',
  'Mascolinità',
  'LGBTQ+',
  'Diritti civili',
  'Giustizia sociale',
  'Attivismo',
  'Volontariato',
  'Filantropia',
  'Carità',
  'Microcredito',
  'Crowdfunding',
  'Sharing economy',
  'Collaborative consumption',
  'Peer-to-peer',
  'Open source',
  'Creative commons',
  'Copyleft',
  'Hacktivism',
  'Cybersecurity',
  'Ethical hacking',
  'Penetration testing',
  'Bug bounty',
  'Digital forensics',
  'Cryptography',
  'Steganography',
  'Digital privacy',
  'Data protection',
  'GDPR',
  'Cookie policy',
  'Terms of service',
  'Privacy policy',
  'User agreement',
  'License agreement',
  'Service level agreement',
  'Memorandum of understanding',
  'Letter of intent',
  'Non-disclosure agreement',
  'Non-compete agreement',
  'Employment contract',
  'Freelance contract',
  'Consulting agreement',
  'Partnership agreement',
  'Joint venture',
  'Merger',
  'Acquisition',
  'IPO',
  'Venture capital',
  'Private equity',
  'Angel investing',
  'Crowdfunding',
  'ICO',
  'STO',
  'DeFi',
  'NFT',
  'Metaverse',
  'Web3',
  'DAO',
  'Smart contracts',
  'DApps',
  'DeFi protocols',
  'Yield farming',
  'Liquidity mining',
  'Staking',
  'Governance tokens',
  'Utility tokens',
  'Security tokens',
  'Stablecoins',
  'CBDC',
  'Digital yuan',
  'Digital euro',
  'Digital dollar',
  'Central bank digital currency',
  'Monetary policy',
  'Fiscal policy',
  'Economic theory',
  'Macroeconomics',
  'Microeconomics',
  'Behavioral economics',
  'Game theory',
  'Decision theory',
  'Risk management',
  'Portfolio theory',
  'Efficient market hypothesis',
  'Random walk theory',
  'Technical analysis',
  'Fundamental analysis',
  'Value investing',
  'Growth investing',
  'Momentum investing',
  'Contrarian investing',
  'Index investing',
  'Passive investing',
  'Active investing',
  'Quantitative investing',
  'Algorithmic trading',
  'High-frequency trading',
  'Arbitrage',
  'Hedging',
  'Derivatives',
  'Options',
  'Futures',
  'Forwards',
  'Swaps',
  'Structured products',
  'Securitization',
  'Credit default swaps',
  'Collateralized debt obligations',
  'Mortgage-backed securities',
  'Asset-backed securities',
  'Commercial paper',
  'Treasury bills',
  'Government bonds',
  'Corporate bonds',
  'Municipal bonds',
  'Junk bonds',
  'Convertible bonds',
  'Zero-coupon bonds',
  'Inflation-linked bonds',
  'Floating rate notes',
  'Perpetual bonds',
  'Callable bonds',
  'Putable bonds',
  'Subordinated debt',
  'Mezzanine debt',
  'Bridge loans',
  'Revolving credit',
  'Term loans',
  'Syndicated loans',
  'Project finance',
  'Trade finance',
  'Export finance',
  'Import finance',
  'Factoring',
  'Forfaiting',
  'Leasing',
  'Hire purchase',
  'Sale and leaseback',
  'Operating lease',
  'Finance lease',
  'Capital lease',
  'Sale and repurchase',
  'Repurchase agreement',
  'Reverse repo',
  'Securities lending',
  'Stock lending',
  'Bond lending',
  'Commodity lending',
  'Currency lending',
  'Interest rate swaps',
  'Currency swaps',
  'Credit default swaps',
  'Total return swaps',
  'Equity swaps',
  'Commodity swaps',
  'Inflation swaps',
  'Volatility swaps',
  'Variance swaps',
  'Correlation swaps',
  'Basis swaps',
  'Cross-currency swaps',
  'Amortizing swaps',
  'Accreting swaps',
  'Rollercoaster swaps',
  'Range accrual swaps',
  'Digital swaps',
  'Barrier options',
  'Asian options',
  'Lookback options',
  'Shout options',
  'Chooser options',
  'Compound options',
  'Exchange options',
  'Rainbow options',
  'Basket options',
  'Spread options',
  'Quanto options',
  'Power options',
  'Log options',
  'Exotic options',
  'Vanilla options',
  'American options',
  'European options',
  'Bermudan options',
  'Canary options',
  'Atlantic options',
  'Pacific options',
  'Asian options',
  'Lookback options',
  'Barrier options',
  'Digital options',
  'Binary options',
  'All-or-nothing options',
  'One-touch options',
  'No-touch options',
  'Double-touch options',
  'Double-no-touch options',
  'Range options',
  'Accrual options',
  'Forward start options',
  'Cliquet options',
  'Ratchet options',
  'Ladder options',
  'Shout options',
  'Swing options',
  'Installment options',
  'Extendible options',
  'Callable options',
  'Putable options',
  'Convertible options',
  'Exchangeable options',
  'Warrants',
  'Covered warrants',
  'Naked warrants',
  'Detachable warrants',
  'Non-detachable warrants',
  'American warrants',
  'European warrants',
  'Bermudan warrants',
  'Perpetual warrants',
  'Callable warrants',
  'Putable warrants',
  'Convertible warrants',
  'Exchangeable warrants',
  'Index warrants',
  'Currency warrants',
  'Commodity warrants',
  'Interest rate warrants',
  'Credit warrants',
  'Volatility warrants',
  'Variance warrants',
  'Correlation warrants',
  'Basis warrants',
  'Cross-currency warrants',
  'Amortizing warrants',
  'Accreting warrants',
  'Rollercoaster warrants',
  'Range accrual warrants',
  'Digital warrants',
  'Barrier warrants',
  'Asian warrants',
  'Lookback warrants',
  'Shout warrants',
  'Chooser warrants',
  'Compound warrants',
  'Exchange warrants',
  'Rainbow warrants',
  'Basket warrants',
  'Spread warrants',
  'Quanto warrants',
  'Power warrants',
  'Log warrants',
  'Exotic warrants',
  'Vanilla warrants',
  'American warrants',
  'European warrants',
  'Bermudan warrants',
  'Canary warrants',
  'Atlantic warrants',
  'Pacific warrants',
  'Asian warrants',
  'Lookback warrants',
  'Barrier warrants',
  'Digital warrants',
  'Binary warrants',
  'All-or-nothing warrants',
  'One-touch warrants',
  'No-touch warrants',
  'Double-touch warrants',
  'Double-no-touch warrants',
  'Range warrants',
  'Accrual warrants',
  'Forward start warrants',
  'Cliquet warrants',
  'Ratchet warrants',
  'Ladder warrants',
  'Shout warrants',
  'Swing warrants',
  'Installment warrants',
  'Extendible warrants',
  'Callable warrants',
  'Putable warrants',
  'Convertible warrants',
  'Exchangeable warrants'
];

// Cucine disponibili
export const availableCuisines = [
  'Italiana',
  'Giapponese',
  'Cinese',
  'Indiana',
  'Messicana',
  'Mediterranea',
  'Vegana',
  'Vegetariana',
  'Fast Food',
  'Fusion',
  'Molecolare',
  'Tradizionale',
  'Contemporanea',
  'Regionale',
  'Internazionale',
  'Gourmet',
  'Street Food',
  'Sostenibile',
  'Biologica',
  'Slow Food'
]; 